keys:
  - &primary age120smthme2cve6kfak2gpnle5nqzzamnj2rmpw9gmr9dwyyvnfahq0fq454
  - &local age166dzurutpwqelp8f8vwc8typhz8psfa5hdn86umndmn3hwtngcdqklj0u5

creation_rules:
  # Vaultwarden helm
  - path_regex: "vaultwarden/secrets/(.*).yaml"
    age: *primary

  # Pgadmin4 kustomize
  - path_regex: "pgadmin/(.*)secret.yaml"
    unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    age: *primary

  # Gitlab docker compose
  - path_regex: "gitlab/.env"
    age: *primary

  # Gitlab local docker compose
  - path_regex: "gitlab-local/.env"
    age: *local
