apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-classrooms-stage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/git-classrooms/git-classrooms.git
    path: deploy/kustomize/stage
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: git-classrooms-stage 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

