apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/git-classrooms/infra.git
    path: vaultwarden
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

