apiVersion: v1
kind: Secret
metadata:
    name: pgadmin4-secret
type: Opaque
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:GKDaG3o/DyyVvDAyFsIVvnkfOATtyQF/wpgrxgJdvBh3LMbT,iv:yQjd8YtbTg+3AwasPPkbUDDePDWZL7eWehwsZ2bxZ5Q=,tag:XyCCDBP+asZiW7LVEwMiMg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:h4i/VAbWa0y+uc0SCM+zzTd71qLva9jWgNU0PNDO6JrJQDVPU+aKzvmt4Wc=,iv:qSwgWdilWdBWxOLD8A346XnthYYN9XlIr9n1suHbc9M=,tag:UamqG/vp4uPfYgTFFLTsFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age120smthme2cve6kfak2gpnle5nqzzamnj2rmpw9gmr9dwyyvnfahq0fq454
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelNFc25VNHB3RVZyUkJN
            ZXNzZDZGMzNWUGhDOHhRM005cnBaN1NmOUZrCmZqWGVqbTQ4MG1vWVhldDZLWmV1
            YW1HS0t2R0dPaWhwejBuaWRuOXZqQ0UKLS0tIEE0dGtNZkxoa1I4YnhCOWc1R0Iy
            RjdiUzA1MUdrcWJpWHZoUlBoODYreVUKLl0v0s+UcgUqNwlYrDaVWsppZz6VIUKb
            XkjRxbqFZCmmOTjKXoPjhth363EVI34N6cO7Kr+zoVYBFG0O/gZQaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T14:56:25Z"
    mac: ENC[AES256_GCM,data:+miziBTMhoQZVpmqwexXrReEjhrLw4nTUhjVE4Uk986KiQENsnwGd1UG7NLuZaHmN8viOzLNZPhZOnpfqEx31dp7ZNbUmn7TuSCvDaZ4keHFXKlZ7bdteIT7g6rzIejiwjAC2HiFuN0kNsH9AwaeVX7nCaLXESZKuJBP1cBjwkg=,iv:PzPZMtaiDUR5gOIelyJqKZcc7mMEzIZtjrm5oBuziAc=,tag:F41/1MJpeg3tji93IJrcrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
