services:
  gitlab:
    image: gitlab/gitlab-ce:17.7.0-ce.0
    restart: unless-stopped
    hostname: "gitlab.git-classrooms.dev"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.git-classrooms.dev'
        nginx['listen_port'] = 8929
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
      GITLAB_ROOT_EMAIL: $GITLAB_ROOT_EMAIL
      GITLAB_ROOT_PASSWORD: $GITLAB_ROOT_PASSWORD
    ports:
      - "8929:8929"
      - "2424:22"
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
    shm_size: "256m"

  gitlab-runner:
    image: gitlab/gitlab-runner:v17.7.0
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "gitlab-runner-config:/etc/gitlab-runner"

volumes:
  gitlab-runner-config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.200,nolock,soft,rw"
      device: ":/volume1/gc01-nfs/docker/gitlab/runner"

  gitlab-config:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.10.200,nolock,soft,rw"
      device: ":/volume1/gc01-nfs/docker/gitlab/config"
  gitlab-logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.10.200,nolock,soft,rw"
      device: ":/volume1/gc01-nfs/docker/gitlab/logs"
  gitlab-data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.10.200,nolock,soft,rw"
      device: ":/volume1/gc01-nfs/docker/gitlab/data"
